package com.xeismonium.fienime.model

object AnimeDataSource {
    val dummyMovieAnime = listOf(
        Anime(
            1,
            R.drawable.,
            "",
            "",
            "",
            ""
        ),
        Anime(
            2,
            R.drawable.,
            "",
            "",
            "",
            ""
        ),
        Anime(
            3,
            R.drawable.,
            "",
            "",
            "",
            ""
        ),
        Anime(
            4,
            R.drawable.,
            "",
            "",
            "",
            ""
        ),Anime(
            5,
            R.drawable.,
            "",
            "",
            "",
            ""
        ),
        Anime(
            6,
            R.drawable.,
            "",
            "",
            "",
            ""
        ),

        Anime(
            7,
            R.drawable.,
            "",
            "",
            "",
            ""
        ),
        Anime(
            8,
            R.drawable.,
            "",
            "",
            "",
            ""
        ),
        Anime(
            9,
            R.drawable.,
            "",
            "",
            "",
            ""
        ),
        Anime(
            10,
            R.drawable.,
            "",
            "",
            "",
            ""
        ),
    )
}